---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: testapp
        ver: 1.0.1
    spec:
      containers:
        - name: testapp
          image: 90188/kub:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP  
